services:
  main-server:
    build:
      context: .
    #      dockerfile: Dockerfile
    ports:
      - "8098:8098"
    volumes:
      - ./uploads:/uploads
    environment:
      - GO111MODULE=on
      - GOPROXY=https://goproxy.cn,direct
      - CGO_ENABLED=0
    env_file:
      - .env
    depends_on:
      - doc-processor
      - deeplx
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8098/health" ]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

  deeplx:
    image: ghcr.io/owo-network/deeplx:latest
    ports:
      - "1188:1188"
  doc-processor:
    build:
      context: ./python_src
    ports:
      - "5000:5000"
#    volumes:
#      - ./python_src:/app
